# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 2017 Open Data Progress Report
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The real promise of Open Data is not about what the City does: It’s about New Yorkers like you. Your right to access government information has long been a cornerstone of modern civics
baseurl: "/2017-Open-Data-Report" # the subpath of your site, e.g. /blog
url: "https://moda-nyc.github.io/2017-Open-Data-Report/" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: UA-102575244-1
twitter_username: NYCAnalytics
github_username:  MODA-NYC

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
